---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kaptain-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/startx/kaptain-operator-catalog:v0.0.7
  displayName: SXApi Operator
  publisher: startx.fr
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kaptain-group
  namespace: openshift-marketplace
spec:
  targetNamespaces:
  - default
  - demo-kaptain
  - kaptain
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kaptain-operator
  namespace: default
spec:
  channel: alpha
  name: kaptain-operator
  source: kaptain-catalog
  sourceNamespace: openshift-marketplace
