apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kaptain.startx.fr/v1alpha1",
          "kind": "KaptainApp",
          "metadata": {
            "name": "kaptainapp-sample"
          },
          "spec": {
            "size": 3
          }
        },
        {
          "apiVersion": "kaptain.startx.fr/v1alpha1",
          "kind": "KaptainService",
          "metadata": {
            "name": "kaptainservice-sample"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: kaptain-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: KaptainApp
      name: kaptainapps.kaptain.startx.fr
      version: v1alpha1
    - kind: KaptainService
      name: kaptainservices.kaptain.startx.fr
      version: v1alpha1
  description: Operator to configure a full cluster in the gitops way.
  displayName: STARTX Kaptain operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kaptain.startx.fr
          resources:
          - kaptainservices
          - kaptainservices/status
          - kaptainservices/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kaptain.startx.fr
          resources:
          - kaptainapps
          - kaptainapps/status
          - kaptainapps/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kaptain-operator-controller-manager
      deployments:
      - name: kaptain-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=kaptain-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/startx/kaptain-operator:0.0.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kaptain-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kaptain-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gitops
  - cluster
  - config
  - service
  - application
  - lifecycle
  links:
  - name: Kaptain Operator
    url: https://kaptain-operator.domain
  maintainers:
  - email: dev@startx.fr
    name: startx
  maturity: alpha
  provider:
    name: STARTX
    url: https://github.com/startxfr/kaptain-operator
  version: 0.0.2
