# permissions for end users to view kaptainapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaptainapp-viewer-role
rules:
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainapps/status
  verbs:
  - get
