# permissions for end users to view kaptainservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaptainservice-viewer-role
rules:
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainservices/status
  verbs:
  - get
