# permissions for end users to edit kaptainapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaptainapp-editor-role
rules:
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaptain.startx.fr
  resources:
  - kaptainapps/status
  verbs:
  - get
