apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kaptain-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  displayName: STARTX Kaptain operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNjUiIGhlaWdodD0iNjUiIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDY1IDY1IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogPHRpdGxlPlNYQVBJIGxvZ288L3RpdGxlPgogPGcgdHJhbnNmb3JtPSJtYXRyaXgoMi45MjEgMCAwIDIuOTIxIC0zMy44ODQgLTc1My45NykiPgogIDxnIGlkPSJhIiB0cmFuc2Zvcm09Im1hdHJpeCguMjgxNCAwIDAgLjI4MTQgOC41ODE4IDIyOC41NykiIGZpbGw9Im5vbmUiPgogICA8cGF0aCBpZD0iYiIgZD0ibTI4LjU5MSAxNzMuODcgMjUuMzY3LTI1LjM3NS0wLjAxOTAxLTE1LjQwMiIgc3Ryb2tlPSIjZmYwZTJmIiBzdHJva2Utd2lkdGg9IjQuOTQ1OCIvPgogICA8ZyBpZD0iYyIgdHJhbnNmb3JtPSJtYXRyaXgoLjM1MzI3IDAgMCAuMzUzMjcgMTAuMzk3IDY5LjUyOSkiIHN0cm9rZT0iIzRkOWVmZiIgc3Ryb2tlLXdpZHRoPSIxNCI+CiAgICA8cGF0aCBkPSJtMTYuODczIDI2Mi4xMiA1My4xODEtNTIuNzY0LTAuMDAyOC00NS40NjQtMTIuMDU1LTExLjc0MSIvPgogICAgPGNpcmNsZSBjeD0iNTAuODUzIiBjeT0iMTQ0LjIzIiByPSIxMi4xMDkiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPgogICA8L2c+CiAgIDxnIGlkPSJkIiBzdHJva2U9IiM4YzAyMTUiPgogICAgPHBhdGggZD0ibTM0LjMzOCAxODAuMTEgMjAuOTc0LTIwLjE2MmgxMy4xOTkiIHN0cm9rZS13aWR0aD0iNC45NDU4Ii8+CiAgICA8cmVjdCB4PSI2OC45OTEiIHk9IjE1NC44NiIgd2lkdGg9IjEwLjQ2NyIgaGVpZ2h0PSIxMC40NjciIHJ4PSIwIiByeT0iMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2Utd2lkdGg9IjQuMjM5MiIvPgogICA8L2c+CiAgIDxnIGlkPSJlIiB0cmFuc2Zvcm09Im1hdHJpeCguMzUzMjcgMCAwIC4zNTMyNyAxMC4zOTcgNjkuNTI5KSIgc3Ryb2tlPSIjMmYxZGZmIj4KICAgIDxwYXRoIGQ9Im0xMjEuMTQgMTM0LjMxLTI4Ljg1NCAyOS4yNTUtMC4wMDkxMDYgNTYuMzc4LTU4LjQzNyA1OS4xNDQiIHN0cm9rZS13aWR0aD0iMTQiLz4KICAgIDxwYXRoIGQ9Im0xMzAuMTcgMTUwLjEzLTI1LjkzOC0yNS45MzggMzUuNDMyLTkuNDkzOXoiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxMiIvPgogICA8L2c+CiAgPC9nPgogPC9nPgo8L3N2Zz4K
    mediatype: image/svg+xml
  description: |-
    ## Overview

    The STARTX Kaptain Operator manages the full lifecycle of a cluster and all it running services and
    applications.  
    
    The operator's goal is to automate the tasks required for day 2 and application workloads dedicated to a cluster.

    Beyond installation, the operator helps to automate the full lifecycle of a cluster and it's workload by defining state
    into your git repositories.
     
    The operator aims to provide the following, and is a work in progress.
    * Configuration of cluster infrastructure management (auto-scalling, machine and cluster management). 
    * Configuration of cluster backend (auth, console tuning and storage). 
    * Configuration of global services 
      * Couchbase
      * Service mesh (istio)
      * Kubevirt
      * Openshift Data Fundation
      * Metering
      * Logging
      * Serverless
      * Tekton
      * Quay Enterprise
      * Vault
      * Workspace
      * Advanced cluster management
      * 3scale
      * SSO (Keycloak)
    * Deployment of application defined into an helm chart (tech preview).

    ## Usage

    Deploy a basic KaptainService
    application by creating a new SXApi resource in your current namespace.

    ```yaml
    apiVersion: kaptain.startx.fr/v1alpha1
    kind: KaptainService
    metadata:
      name: config-kaptain
    spec: 
    context:
      app: config-kaptain
      component: kaptain
      environment: example
      scope: example
      version: 0.0.7
    kaptain:
      data: |
        kaptain.yml: |-
            name: example
            description: Description of the example kaptain instance (defined in kaptain operator)
            version: "0.3.57"
            debug: false
            resources:
              serviceinfo-sample:
                _class: serviceinfo
            log:
              filters:
                level: '0,1,2,3,4'
                type: debug,info,error,warn
            server:
              port: '8077'
              endpoints:
              - path: "/"
                body: |-
                    <html>
                    <head><title>Example application (operator default values)</title></head>
                    <body> 
                      <h1>SXAPI is live ! (operator's managed)</h1>
                      <p> 
                        This example is deployed using the kaptain operator example based on the 
                        <a href="https://helm-repository.readthedocs.io/en/latest/charts/kaptain.html" target="_blank">kaptain chart</a>
                        available in the <a href="https://helm-repository.readthedocs.io" target="_blank">startx helm repository</a>. 
                      </p>
                      <p> 
                        You could check the following endpoints :</p>
                      <ul>
                        <li><a href="./health">Health status (used by readiness probe)</a></li>
                        <li><a href="./info">Information about the application</a></li>
                      </ul>
                    </body>
                    </html> 
              - path: "/health"
                resource: serviceinfo-sample
                endpoint:
    health
        expose:
          enabled: true
        replicas: 3
    ```
    See the [documentation](https://kaptain.readthedocs.io)
    and examples on [github](https://github.com/startxfr/kaptain-operator) for more information.
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gitops
  - cluster
  - config
  - service
  - application
  - lifecycle
  links:
  - name: Kaptain Operator
    url: https://kaptain-operator.domain
  maintainers:
  - email: dev@startx.fr
    name: startx
  maturity: alpha
  provider:
    name: STARTX
    url: https://github.com/startxfr/kaptain-operator
  replaces: kaptain-operator.v0.0.1
  version: 0.0.2
