---
# tasks file for KaptainApp
- name: start testing app pod
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-app-test'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: test
        template:
          metadata:
            labels:
              app: test
          spec:
            containers:
            - name: test
              command:
              - sx-apache
              - run
              image: "quay.io/startx/apache:latest"
              ports:
                - containerPort: 8080
